// Run: node tests/habit.browser.cjs [path-to-playwright-package]
const {chromium}=require(process.argv[2]||'playwright');
const assert=require('node:assert/strict');
const http=require('node:http');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{
  const name=req.url==='/'?'index.html':req.url.slice(1).split('?')[0];
  const file=path.resolve(root,name);
  if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}
  fs.readFile(file,(err,data)=>{if(err){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.json')?'application/json':'text/html');res.end(data);});
});
(async()=>{
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const browser=await chromium.launch({headless:true});
  try {
    const context=await browser.newContext({viewport:{width:390,height:844},timezoneId:'America/Los_Angeles'});
    const page=await context.newPage(), errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    await page.clock.install({time:new Date('2026-09-10T02:00:00Z')});
    await page.goto(`http://127.0.0.1:${server.address().port}/`);
    await page.waitForSelector('#quickStart');
    assert.equal(await page.locator('.hero').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(20, 63, 53)','Hero keeps readable contrast');
    assert.equal(await page.evaluate(()=>todayKey()),'2026-09-09','Date uses local day');
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Mobile layout fits');
    await page.click('#restToday');
    assert.match(await page.locator('#habitHome').innerText(),/Room to recover/);
    assert.equal(await page.locator('#sessions7').innerText(),'0','Rest is not activity');
    await page.click('#quickStart');
    const swipe=async(dx,dy=0)=>{const box=await page.locator('.swipe-card').boundingBox();const x=box.x+box.width/2,y=box.y+50;await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+dx,y+dy,{steps:8});await page.mouse.up();};
    await swipe(-100);
    assert.equal(await page.evaluate(()=>get('habitDraft',null).index),1,'Swipe left moves to next card');
    await swipe(100);
    assert.equal(await page.evaluate(()=>get('habitDraft',null).index),0,'Swipe right moves to previous card');
    await swipe(5,80);
    assert.equal(await page.evaluate(()=>get('habitDraft',null).index),0,'Vertical drag does not change card');
    const touch=await context.newCDPSession(page);
    const touchBox=await page.locator('.swipe-card').boundingBox();
    const touchX=touchBox.x+touchBox.width-35,touchY=touchBox.y+60;
    await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:touchX,y:touchY}]});
    await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:touchX-120,y:touchY}]});
    await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
    assert.equal(await page.evaluate(()=>get('habitDraft',null).index),1,'Real touch swipe advances card');
    await page.click('#guidePrevious');await touch.detach();
    await page.locator('.swipe-card').focus();await page.keyboard.press('ArrowRight');
    assert.equal(await page.evaluate(()=>get('habitDraft',null).index),1,'Arrow-key navigation works');
    page.once('dialog',d=>d.dismiss());await page.click('#guideReset');
    assert.equal(await page.evaluate(()=>get('habitDraft',null).index),1,'Cancel reset preserves position');
    page.once('dialog',d=>d.accept());await page.click('#guideReset');
    assert.equal(await page.evaluate(()=>get('habitDraft',null).index),0,'Reset returns to first card');
    await page.click('#guideSkip');
    await page.click('#guideSkip');
    await page.click('#guideSave');
    assert.equal(await page.evaluate(()=>get('habitSessions',[]).length),0,'Skipping does not earn activity');
    await page.click('#quickStart');
    await page.click('#guideToggle');
    await page.screenshot({path:path.join(root,'tests','guide-mobile.png')});
    await page.clock.runFor(20000);
    await page.click('#guideClose');
    const draft=await page.evaluate(()=>get('habitDraft',null));
    assert.ok(draft.elapsed>=4 && draft.elapsed<=6,'Only movement time is counted');
    await page.reload();await page.waitForSelector('#quickStart');
    assert.match(await page.locator('#quickStart').innerText(),/Resume/);
    await page.click('#quickStart');
    assert.equal(await page.locator('#guideToggle').innerText(),'Continue','Resumed session is paused');
    await page.click('#guideToggle');await page.clock.runFor(40000);
    assert.equal(await page.evaluate(()=>get('habitSessions',[]).length),0,'Timer alone does not save exercise');
    await page.click('#guideDone');
    await page.click('#guidePrevious');
    assert.equal(await page.locator('#guideDone').isDisabled(),true,'Revisiting a completed card cannot duplicate credit');
    await page.click('#guideSkip');await page.click('#guideSkip');
    await page.selectOption('#guideEffort','Hard');await page.selectOption('#guideDiscomfort','yes');
    await page.click('#guideSave');
    const records=await page.evaluate(()=>get('habitSessions',[]));
    assert.equal(records.length,1);assert.equal(records[0].steps.length,1);assert.equal(records[0].activeSeconds,45);
    assert.equal(await page.locator('#sessions7').innerText(),'1');
    assert.equal(await page.evaluate(()=>get('habitDraft',null)),null);
    await page.click('#quickStart');await page.click('#guideToggle');await page.clock.runFor(20000);await page.click('#guideDone');
    page.once('dialog',d=>d.accept());await page.click('#guideReset');
    assert.equal(await page.evaluate(()=>get('habitDraft',null).steps.length),0,'Reset clears unsaved movements');
    assert.equal(await page.evaluate(()=>get('habitSessions',[]).length),1,'Reset preserves saved journal');
    await page.click('#guideFinish');await page.click('#guideSave');
    assert.match(await page.locator('#habitHome').innerText(),/lighter after your last feedback/);
    await page.evaluate(()=>{const d=daily();d.knee=5;saveDaily(d);});
    assert.deepEqual(await page.evaluate(()=>Habit.candidates().map(e=>e.id)),['armcircles'],'Knee report filters movements');
    assert.equal(await page.evaluate(()=>{set('progressLogs',[{rpe:null,recovery:null},{rpe:0,recovery:0}]);return recommendation().includes('add');}),false,'Missing values do not trigger progression');
    await page.click('[data-tab="boxing"]');
    await page.evaluate(()=>{setBoxing(1,1,2);startTimer();});
    await page.clock.runFor(3000);
    await page.click('#guideSave');
    assert.equal(await page.evaluate(()=>get('habitSessions',[]).length),2,'Boxing records after confirmation');
    await page.evaluate(()=>startTimer());await page.clock.runFor(1000);
    assert.equal(await page.evaluate(()=>get('habitSessions',[]).length),2,'Finished timer cannot duplicate record');
    await page.click('[data-tab="progress"]');
    assert.match(await page.locator('#habitProgress').innerText(),/Boxing intervals/);
    await page.screenshot({path:path.join(root,'tests','progress-mobile.png'),fullPage:true});
    await page.click('[data-tab="today"]');
    await page.setViewportSize({width:1280,height:900});
    await page.screenshot({path:path.join(root,'tests','today-desktop.png'),fullPage:true});
    // New UI: inspect every section at phone, tablet, and desktop sizes.
    for(const width of [390,820,1440]){
      await page.setViewportSize({width,height:900});
      for(const tab of ['today','boxing','progress','nutrition','settings']){
        await page.click(`[data-tab="${tab}"]`);
        assert.equal(await page.locator(`[data-tab="${tab}"]`).getAttribute('aria-selected'),'true');
        assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${tab} fits at ${width}px`);
        await page.screenshot({path:path.join(root,'tests',`ui-${tab}-${width}.png`),fullPage:true});
      }
    }
    await page.click('[data-tab="nutrition"]');
    await page.click('[data-food="6"]');
    assert.equal(await page.locator('#qty').inputValue(),'200');
    assert.equal(await page.locator('#foodPreview').innerText(),'6.4 g');
    await page.click('.food-entry .button-dark');
    assert.equal(await page.locator('#proteinTotal').innerText(),'6.4 g');
    assert.match(await page.locator('#foodLog').innerText(),/Milk/);
    await page.fill('#qty','-10');
    await page.click('.food-entry .button-dark');
    assert.equal(await page.evaluate(()=>get('protein-'+todayKey(),[]).length),1,'Invalid portions are not saved');
    await page.click('[data-tab="progress"]');
    await page.click('.page-heading .button-dark');
    assert.equal(await page.locator('#weeklyCheckin').evaluate(el=>el.open),true);
    await page.click('[data-tab="settings"]');
    const downloadPromise=page.waitForEvent('download');
    await page.click('.backup-card .button-dark');
    assert.match((await downloadPromise).suggestedFilename(),/body-tracker-backup/);
    await page.locator('[data-tab="settings"]').focus();
    await page.keyboard.press('Home');
    assert.equal(await page.locator('[data-tab="today"]').getAttribute('aria-selected'),'true','Keyboard navigation works');
    // Existing checkmarks still contribute without double-counting a session day.
    assert.equal(await page.evaluate(()=>{const d=daily();d.done.armcircles=true;saveDaily(d);Habit.refresh();return document.getElementById('sessions7').textContent;}),'1');
    await page.evaluate(async()=>{await navigator.serviceWorker.ready;});
    await page.reload();await page.waitForSelector('#quickStart');
    assert.ok(await page.evaluate(()=>!!navigator.serviceWorker.controller),'Service worker controls the page');
    await context.setOffline(true);
    await page.reload();await page.waitForSelector('#quickStart');
    assert.equal(await page.locator('.hero').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(20, 63, 53)','Offline styles load');
    assert.equal(await page.evaluate(()=>get('habitSessions',[]).length),2,'Offline reload retains journal');
    await context.setOffline(false);
    await page.clock.setSystemTime(new Date('2026-09-10T08:00:00Z'));
    await page.evaluate(()=>window.dispatchEvent(new Event('focus')));
    assert.equal(await page.evaluate(()=>todayKey()),'2026-09-10');
    assert.match(await page.locator('#todayDate').innerText(),/10/,'Open app rolls into the new local day');
    assert.deepEqual(errors,[],'No browser errors');
    console.log('PASS: local dates and rollover, mobile fit, contrast, rest, skips, resume, timing, confirmation, feedback adaptation, filtering, missing data, boxing, duplicate prevention, legacy records and offline reload.');
    await context.close();
  } finally {await browser.close();server.close();}
})().catch(error=>{console.error(error);server.close();process.exitCode=1;});
